                               database name
http://conf.cmsfs.com/monitor/diskSpace/p_c/:server
http://conf.cmsfs.com/monitor/diskSpace/p_es/:server
http://conf.cmsfs.com/monitor/diskSpace/p_np/:server