version: '2.1'

services:
  kafka-server:
    image: cmsfs/kafka-server
    container_name: kafka-server
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "9092:9092"
    networks:
      cmsfs:
        aliases:
          - kafka-server.cmsfs.org
  zookeeper-server:
    image: cmsfs/zookeeper-server
    container_name: zookeeper-server
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      cmsfs:
        aliases:
          - zookeeper-server.cmsfs.org
    ports:
      - "2181:2181"

  cmsfs:
    image: cmsfs:latest
    container_name: cmsfs_cmsfs
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
    networks:
      - cmsfs
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  mysql:
    image: mysql
    container_name: cmsfs_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456aA+
    volumes:
      - ./mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    networks:
      cmsfs:
        aliases:
          - mysql.cmsfs.org
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ss -lt | grep mysql"]
      interval: 3s
      timeout: 2s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: cmsfs_elasticsearch
    networks:
      cmsfs:
        aliases:
          - elasticsearch.cmsfs.org
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    mem_limit: 3g
    volumes:
      - ./elasticsearch/esdata:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    ports:
      - "9200:9200"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

  grafana:
    image: grafana/grafana
    container_name: cmsfs_grafana
    networks:
      - cmsfs
    volumes:
      - /etc/localtime:/etc/localtime
      - ./grafana/data:/var/lib/grafana
      # - ./grafana/config:/etc/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456aA+
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"

networks:
   cmsfs:
    driver: bridge